# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shelver}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Zumwalt"]
  s.date = %q{2010-05-10}
  s.description = %q{Use shelver to populate solr indexes from Fedora repository content or from other sources.  You can run shelver from within your apps, using the provided rake tasks, or as a JMS listener}
  s.email = %q{matt.zumwalt@yourmediashelf.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/hydra_types.yml",
     "config/solr.yml",
     "lib/shelver.rb",
     "lib/shelver/configuration.rb",
     "lib/shelver/extractor.rb",
     "lib/shelver/indexer.rb",
     "lib/shelver/main.rb",
     "lib/shelver/replicator.rb",
     "lib/shelver/repository.rb",
     "lib/tasks/shelver.rake",
     "shelver.gemspec",
     "spec/fixtures/druid-bv448hq0314-descMetadata.xml",
     "spec/fixtures/druid-bv448hq0314-extProperties.xml",
     "spec/fixtures/druid-cm234kq4672-extProperties.xml",
     "spec/fixtures/druid-cm234kq4672-stories.xml",
     "spec/fixtures/druid-hc513kw4806-descMetadata.xml",
     "spec/fixtures/rels_ext_cmodel.xml",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/units/extractor_spec.rb",
     "spec/units/indexer_spec.rb",
     "spec/units/shelver_spec.rb"
  ]
  s.homepage = %q{http://github.com/mediashelf/shelver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A utility for building solr indexes, usually from Fedora repository content.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/units/extractor_spec.rb",
     "spec/units/indexer_spec.rb",
     "spec/units/shelver_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

